<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PAHOHTD" failures="1" tests="5" name="Test" time="126.11" errors="0" timestamp="2022-08-23T15:46:00 IST">
  <testcase classname="com.qa.testLayer.TradingTest" name="buyShareAxis" time="17.358">
    <failure type="java.lang.AssertionError" message="expected [Order Created ccessfully] but found [Order Created successfully]">
      <![CDATA[java.lang.AssertionError: expected [Order Created ccessfully] but found [Order Created successfully]
at com.qa.testLayer.TradingTest.buyShareAxis(TradingTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- buyShareAxis -->
  <testcase classname="com.qa.testLayer.TradingTest" name="buyShareGail" time="18.019"/>
  <testcase classname="com.qa.testLayer.TradingTest" name="buyShareWipro" time="17.169"/>
  <testcase classname="com.qa.testLayer.TradingTest" name="sellShareGail" time="17.461"/>
  <testcase classname="com.qa.testLayer.TradingTest" name="sellShareWipro" time="17.234"/>
</testsuite> <!-- Test -->
